#!/bin/bash

# This script sets up Namada and Gaia locally
# `make build` and `make build-wasm-scripts` on Namada directory in advance
# Run with `namada-gaia-simple-transfers ${namada_dir}`

set -e

NAMADA_DIR=$1
if [ -z "${NAMADA_DIR}" ]
then
  echo "ERROR: Namada directory should be given"
  exit 1
fi
cd $(dirname $0)
HERMES_DIR=${PWD%/e2e*}

# edit for your environment
NAMADAC="${NAMADA_DIR}/target/debug/namadac"
NAMADAN="${NAMADA_DIR}/target/debug/namadan"
NAMADAW="${NAMADA_DIR}/target/debug/namadaw"
DATA_DIR="${HERMES_DIR}/data"
IBC_TOKEN="transfer/channel-0/samoleans"

SHIELDED_ALIAS_A="shielded_a"
SHIELDED_ALIAS_B="shielded_b"
PAYMENT_ALIAS_A="payment_a"
PAYMENT_ALIAS_B="payment_b"
NAMADA_LEDGER_ADDR="http://127.0.0.1:27657"

GAIA_CHAIN_CONFIG="
[[chains]]
id = 'gaia-0'
type = 'CosmosSdk'
rpc_addr = 'http://127.0.0.1:26657'
grpc_addr = 'http://127.0.0.1:9090'
event_source = { mode = 'push', url = 'ws://127.0.0.1:26657/websocket', batch_delay = '500ms' }
account_prefix = 'cosmos'
key_name = 'testkey'
store_prefix = 'ibc'
gas_price = { price = 0.001, denom = 'stake' }
"

#### main ####
mkdir -p ${DATA_DIR}

# Gaia
rm -rf ${DATA_DIR}/gaia-0

${HERMES_DIR}/scripts/one-chain gaiad gaia-0 ${DATA_DIR} \
  26657 26656 6060 9090 10000

# Namada
${HERMES_DIR}/scripts/setup-namada-single-node ${NAMADA_DIR}
base_dir=${DATA_DIR}/namada

cd ${HERMES_DIR}
chain_id=$(grep id config_for_namada.toml | sed -e s/\'//g | awk '{print $3}')

# Add Gaia chain config
echo "${GAIA_CHAIN_CONFIG}" >> config_for_namada.toml

# add Gaia key
cargo run -q --bin hermes -- --config config_for_namada.toml \
  keys add --chain gaia-0 --key-file ${DATA_DIR}/gaia-0/user_seed.json --overwrite

# setup Namada shielded keys
${NAMADAW} --base-dir ${base_dir} gen --shielded --alias ${SHIELDED_ALIAS_A} --unsafe-dont-encrypt
${NAMADAW} --base-dir ${base_dir} gen-payment-addr --alias ${PAYMENT_ALIAS_A} --key ${SHIELDED_ALIAS_A}
payment_addr_a=$(${NAMADAW} --base-dir ${base_dir} find --alias ${PAYMENT_ALIAS_A} | awk -v paymentAlias="${PAYMENT_ALIAS_A}" '{if($1 ~ paymentAlias) {print $2}}')

${NAMADAW} --base-dir ${base_dir} gen --shielded --alias ${SHIELDED_ALIAS_B} --unsafe-dont-encrypt
${NAMADAW} --base-dir ${base_dir} gen-payment-addr --alias ${PAYMENT_ALIAS_B} --key ${SHIELDED_ALIAS_B}
payment_addr_b=$(${NAMADAW} --base-dir ${base_dir} find --alias ${PAYMENT_ALIAS_B} | awk -v paymentAlias="${PAYMENT_ALIAS_B}" '{if($1 ~ paymentAlias) {print $2}}')

# Initialize Relayer's balance on Namada
${NAMADAC} --base-dir ${base_dir} \
  transfer \
  --source albert \
  --target relayer \
  --token nam \
  --amount 10000 \
  --node ${NAMADA_LEDGER_ADDR}

${NAMADAC} --base-dir ${base_dir} \
  transfer \
  --source albert \
  --target relayer \
  --token apfel \
  --amount 1000 \
  --node ${NAMADA_LEDGER_ADDR}

# create a channel
cargo run --bin hermes -- --config config_for_namada.toml \
  create channel --a-chain ${chain_id} \
  --b-chain gaia-0 \
  --a-port transfer \
  --b-port transfer \
  --new-client-connection --yes

echo "~~ Transfer 100 samoleans from Gaia to Namada ~~"
namada_receiver=$(${NAMADAW} --base-dir ${base_dir} find --alias relayer | awk '/"relayer":/{print $3}')
cargo run --bin hermes -- --config config_for_namada.toml \
  tx ft-transfer \
  --dst-chain ${chain_id} \
  --src-chain gaia-0 \
  --src-port transfer \
  --src-channel channel-0 \
  --amount 100 \
  --receiver ${namada_receiver} \
  --denom samoleans \
  --timeout-height-offset 1000

# packet-recv
cargo run --bin hermes -- --config config_for_namada.toml \
  tx packet-recv \
  --dst-chain ${chain_id} \
  --src-chain gaia-0 \
  --src-port transfer \
  --src-channel channel-0

# packet-ack
cargo run --bin hermes -- --config config_for_namada.toml \
  tx packet-ack \
  --dst-chain gaia-0 \
  --src-chain ${chain_id} \
  --src-port transfer \
  --src-channel channel-0

echo "==== Balances on Namada ===="
${NAMADAC} --base-dir ${base_dir} balance \
  --token ${IBC_TOKEN} \
  --owner relayer \
  --node ${NAMADA_LEDGER_ADDR}

echo "==== Balances on Gaia ===="
gaia_user=$(gaiad --home ${DATA_DIR}/gaia-0 \
  keys --keyring-backend="test" show user -a)
gaiad query bank balances ${gaia_user}

echo "~~ Transfer back 50 samoleans from Namada to Gaia ~~"
${NAMADAC} --base-dir ${base_dir} ibc-transfer \
  --source relayer \
  --receiver ${gaia_user} \
  --token ${IBC_TOKEN} \
  --amount 50 \
  --signing-keys relayer \
  --channel-id channel-0 \
  --node ${NAMADA_LEDGER_ADDR}

# packet-recv
cargo run --bin hermes -- --config config_for_namada.toml \
  tx packet-recv \
  --dst-chain gaia-0 \
  --src-chain ${chain_id} \
  --src-port transfer \
  --src-channel channel-0

# packet-ack
cargo run --bin hermes -- --config config_for_namada.toml \
  tx packet-ack \
  --dst-chain ${chain_id} \
  --src-chain gaia-0 \
  --src-port transfer \
  --src-channel channel-0

echo "==== Balances on Namada ===="
${NAMADAC} --base-dir ${base_dir} balance \
  --token ${IBC_TOKEN} \
  --owner relayer \
  --node ${NAMADA_LEDGER_ADDR}

echo "==== Balances on Gaia ===="
gaiad query bank balances ${gaia_user}

echo "==== Start Hermes ===="
cargo run --bin hermes -- --config config_for_namada.toml \
  start > ${HERMES_DIR}/e2e/hermes.log 2>&1 &

echo "~~ Transfer 200 apfel from Namada to Gaia ~~"
${NAMADAC} --base-dir ${base_dir} ibc-transfer \
  --source relayer \
  --receiver ${gaia_user} \
  --token apfel \
  --amount 200 \
  --signing-keys relayer \
  --channel-id channel-0 \
  --node ${NAMADA_LEDGER_ADDR}

# wait for relaying
sleep 15

echo "==== Balances on Namada ===="
${NAMADAC} --base-dir ${base_dir} balance \
  --owner relayer \
  --show-ibc-tokens \
  --node ${NAMADA_LEDGER_ADDR}

echo "==== Balances on Gaia ===="
gaiad query bank balances ${gaia_user}

echo "~~ Shielding transfer 10 samoleans from Gaia to Namada ~~"
cargo run --bin hermes -- --config config_for_namada.toml \
  tx ft-transfer \
  --dst-chain ${chain_id} \
  --src-chain gaia-0 \
  --src-port transfer \
  --src-channel channel-0 \
  --amount 10 \
  --receiver ${payment_addr_a} \
  --denom samoleans \
  --timeout-height-offset 1000 \

# wait for relaying
sleep 40

echo "==== Balance of shielded_a on Namada ===="
${NAMADAC} --base-dir ${base_dir} shielded-sync \
  --viewing-keys ${SHIELDED_ALIAS_A} \
  --node ${NAMADA_LEDGER_ADDR}
${NAMADAC} --base-dir ${base_dir} balance \
  --owner ${SHIELDED_ALIAS_A} \
  --show-ibc-tokens \
  --node ${NAMADA_LEDGER_ADDR}

echo "==== Balances on Gaia ===="
gaiad query bank balances ${gaia_user}

echo "~~ Shielded transfer 5 apfel from shielded_a to shielded_b ~~"
${NAMADAC} --base-dir ${base_dir} transfer \
  --source ${SHIELDED_ALIAS_A} \
  --target ${payment_addr_b} \
  --token ${IBC_TOKEN} \
  --amount 5 \
  --signing-keys relayer \
  --node ${NAMADA_LEDGER_ADDR}

echo "==== Balance of shielded_a on Namada ===="
${NAMADAC} --base-dir ${base_dir} shielded-sync \
  --viewing-keys ${SHIELDED_ALIAS_A} ${SHIELDED_ALIAS_B} \
  --node ${NAMADA_LEDGER_ADDR}
${NAMADAC} --base-dir ${base_dir} balance \
  --owner ${SHIELDED_ALIAS_A} \
  --show-ibc-tokens \
  --node ${NAMADA_LEDGER_ADDR}

echo "==== Balance of shielded_b on Namada ===="
${NAMADAC} --base-dir ${base_dir} balance \
  --owner ${SHIELDED_ALIAS_B} \
  --show-ibc-tokens \
  --node ${NAMADA_LEDGER_ADDR}

echo "~~ Transfer back 5 samoleans from Namada to Gaia ~~"
${NAMADAC} --base-dir ${base_dir} ibc-transfer \
  --source ${SHIELDED_ALIAS_B} \
  --receiver ${gaia_user} \
  --token ${IBC_TOKEN} \
  --amount 5 \
  --signing-keys relayer \
  --channel-id channel-0 \
  --node ${NAMADA_LEDGER_ADDR}

# wait for relaying
sleep 40

echo "==== Balances of shielded_a on Namada ===="
${NAMADAC} --base-dir ${base_dir} shielded-sync \
  --viewing-keys ${SHIELDED_ALIAS_A} ${SHIELDED_ALIAS_B} \
  --node ${NAMADA_LEDGER_ADDR}
${NAMADAC} --base-dir ${base_dir} balance \
  --owner ${SHIELDED_ALIAS_A} \
  --show-ibc-tokens \
  --node ${NAMADA_LEDGER_ADDR}

echo "==== Balances of shielded_b on Namada ===="
${NAMADAC} --base-dir ${base_dir} balance \
  --owner ${SHIELDED_ALIAS_B} \
  --show-ibc-tokens \
  --node ${NAMADA_LEDGER_ADDR}

echo "==== Balances on Gaia ===="
gaiad query bank balances ${gaia_user}

killall hermes
killall gaiad
killall namadan
