#!/bin/bash

# This script executes simple transfers between Namada instances locally
# `make build` and `make build-wasm-scripts` on Namada directory in advance
# Run with `namada-simple-transfers ${namada_dir}`

set -e

NAMADA_DIR=$1
if [ -z "${NAMADA_DIR}" ]
then
  echo "ERROR: Namada directory should be given"
  exit 1
fi
cd $(dirname $0)
HERMES_DIR=${PWD%/e2e*}

NAMADAC="${NAMADA_DIR}/target/debug/namadac"
NAMADAW="${NAMADA_DIR}/target/debug/namadaw"
DATA_DIR="${HERMES_DIR}/data"
IBC_TOKEN="transfer/channel-0/apfel"

SHIELDED_ALIAS_A="shielded_a"
SHIELDED_ALIAS_B="shielded_b"
SHIELDED_ALIAS_B_2="shielded_b_2"
PAYMENT_ALIAS_A="payment_a"
PAYMENT_ALIAS_B="payment_b"
PAYMENT_ALIAS_B_2="payment_b_2"
LEDGER_ADDR_A="http://127.0.0.1:27657"
LEDGER_ADDR_B="http://127.0.0.1:28657"
INITIAL_BALANCE=5000

function init_relayer_balance() {
  local suffix=$1
  local ledger_addr=$2

  local base_dir=${DATA_DIR}/namada-${suffix}

  ${NAMADAC} --base-dir ${base_dir} \
    transparent-transfer \
    --source albert \
    --target relayer \
    --token nam \
    --amount ${INITIAL_BALANCE} \
    --node ${ledger_addr}
}

function wait_for_relaying() {
  local chain_id=$1

  for i in {1..20}
  do
    result=$(cargo run --bin hermes -- --config config_for_namada.toml \
      query packet pending \
      --chain ${chain_id} \
      --channel channel-0 \
      --port transfer)

    echo ${result}
    if [[ "${result}" =~ "=" ]];
    then
      echo "Waiting for packet relaying..."
      sleep 5
    else
      echo "All packets have been relayed!"
      break
    fi
  done
}

# ==== main ====

# Run 2 Namada chains
${HERMES_DIR}/scripts/setup-namada ${NAMADA_DIR}
sleep 5

cd ${HERMES_DIR}
ids=$(grep "id" config_for_namada.toml | awk -F"'" '/^id/ {print $2}')
chain_a=$(echo ${ids} | awk '{print $1}')
chain_b=$(echo ${ids} | awk '{print $2}')

# Initialize the balances
init_relayer_balance "a" ${LEDGER_ADDR_A}
sleep 5
init_relayer_balance "b" ${LEDGER_ADDR_B}

# Create a channel
cargo run --bin hermes -- --config config_for_namada.toml \
  create channel \
  --a-chain ${chain_a} \
  --b-chain ${chain_b} \
  --a-port transfer \
  --b-port transfer \
  --new-client-connection --yes

base_dir_a=${DATA_DIR}/namada-a
base_dir_b=${DATA_DIR}/namada-b

# Setup shielded keys
${NAMADAW} --base-dir ${base_dir_a} gen --shielded --alias ${SHIELDED_ALIAS_A} --unsafe-dont-encrypt
${NAMADAW} --base-dir ${base_dir_a} gen-payment-addr --alias ${PAYMENT_ALIAS_A} --key ${SHIELDED_ALIAS_A}
payment_addr_a=$(${NAMADAW} --base-dir ${base_dir_a} find --alias ${PAYMENT_ALIAS_A} | awk -v paymentAlias="${PAYMENT_ALIAS_A}" '{if($1 ~ paymentAlias) {print $2}}')

${NAMADAW} --base-dir ${base_dir_b} gen --shielded --alias ${SHIELDED_ALIAS_B} --unsafe-dont-encrypt
${NAMADAW} --base-dir ${base_dir_b} gen-payment-addr --alias ${PAYMENT_ALIAS_B} --key ${SHIELDED_ALIAS_B}
payment_addr_b=$(${NAMADAW} --base-dir ${base_dir_b} find --alias ${PAYMENT_ALIAS_B} | awk -v paymentAlias="${PAYMENT_ALIAS_B}" '{if($1 ~ paymentAlias) {print $2}}')

${NAMADAW} --base-dir ${base_dir_b} gen --shielded --alias ${SHIELDED_ALIAS_B_2} --unsafe-dont-encrypt
${NAMADAW} --base-dir ${base_dir_b} gen-payment-addr --alias ${PAYMENT_ALIAS_B_2} --key ${SHIELDED_ALIAS_B_2}
payment_addr_b_2=$(${NAMADAW} --base-dir ${base_dir_b} find --alias ${PAYMENT_ALIAS_B_2} | awk -v paymentAlias="${PAYMENT_ALIAS_B_2}" '{if($1 ~ paymentAlias) {print $2}}')

# Faucet apfel on chain A and chain B
${NAMADAC} --base-dir ${base_dir_a} transparent-transfer \
  --source albert \
  --target relayer \
  --token apfel \
  --amount 1000 \
  --signing-keys albert-key \
  --node ${LEDGER_ADDR_A}

${NAMADAC} --base-dir ${base_dir_b} transparent-transfer \
  --source albert \
  --target relayer \
  --token apfel \
  --amount 1000 \
  --signing-keys albert-key \
  --node ${LEDGER_ADDR_B}

# Faucet apfel for shielded_a
${NAMADAC} --base-dir ${base_dir_a} shield \
  --source albert \
  --target ${payment_addr_a} \
  --token apfel \
  --amount 1000 \
  --signing-keys albert-key \
  --node ${LEDGER_ADDR_A}
${NAMADAC} --base-dir ${base_dir_a} shielded-sync \
  --viewing-keys ${SHIELDED_ALIAS_A} \
  --node ${LEDGER_ADDR_A}

# Get the receiver addresses
receiver_a=$(${NAMADAW} --base-dir ${base_dir_a} find --alias relayer | awk '/"relayer":/{print $3}')
receiver_b=$(${NAMADAW} --base-dir ${base_dir_b} find --alias relayer | awk '/"relayer":/{print $3}')

echo "~~ Transfer 100 apfel from chain A to chain B ~~"
${NAMADAC} --base-dir ${base_dir_a} ibc-transfer \
  --source relayer \
  --receiver ${receiver_b} \
  --token apfel \
  --amount 100 \
  --signing-keys relayer \
  --channel-id channel-0 \
  --node ${LEDGER_ADDR_A}

# packet-recv
cargo run --bin hermes -- --config config_for_namada.toml \
  tx packet-recv \
  --dst-chain ${chain_b} \
  --src-chain ${chain_a} \
  --src-port transfer \
  --src-channel channel-0

# packet-ack
cargo run --bin hermes -- --config config_for_namada.toml \
  tx packet-ack \
  --dst-chain ${chain_a} \
  --src-chain ${chain_b} \
  --src-port transfer \
  --src-channel channel-0

echo "==== Balances on chain A ===="
balance=$(${NAMADAC} --base-dir ${base_dir_a} balance \
  --token apfel \
  --owner relayer \
  --node ${LEDGER_ADDR_A})
echo ${balance}
if [ "${balance}" != "apfel: 900" ]; then
  echo "The balance on chain A is wrong"
  exit 1
fi

echo "==== Balances on chain B ===="
balance=$(${NAMADAC} --base-dir ${base_dir_b} balance \
  --token ${IBC_TOKEN} \
  --owner relayer \
  --node ${LEDGER_ADDR_B})
echo ${balance}
if [ "${balance}" != "${IBC_TOKEN}: 100000000" ]; then
  echo "The balance on chain B is wrong"
  exit 1
fi

echo "~~ Transfer back 50 apfel from chain B to chain A ~~"
${NAMADAC} --base-dir ${base_dir_b} ibc-transfer \
  --source relayer \
  --receiver ${receiver_a} \
  --token ${IBC_TOKEN} \
  --amount 50000000 \
  --signing-keys relayer \
  --channel-id channel-0 \
  --node ${LEDGER_ADDR_B}

# packet-recv
cargo run --bin hermes -- --config config_for_namada.toml \
  tx packet-recv \
  --dst-chain ${chain_a} \
  --src-chain ${chain_b} \
  --src-port transfer \
  --src-channel channel-0

# packet-ack
cargo run --bin hermes -- --config config_for_namada.toml \
  tx packet-ack \
  --dst-chain ${chain_b} \
  --src-chain ${chain_a} \
  --src-port transfer \
  --src-channel channel-0

echo "==== Balances on chain A ===="
balance=$(${NAMADAC} --base-dir ${base_dir_a} balance \
  --token apfel \
  --owner relayer \
  --node ${LEDGER_ADDR_A})
echo ${balance}
if [ "${balance}" != "apfel: 950" ]; then
  echo "The balance on chain A is wrong"
  exit 1
fi

echo "==== Balances on chain B ===="
balance=$(${NAMADAC} --base-dir ${base_dir_b} balance \
  --token ${IBC_TOKEN} \
  --owner relayer \
  --node ${LEDGER_ADDR_B})
echo ${balance}
if [ "${balance}" != "${IBC_TOKEN}: 50000000" ]; then
  echo "The balance on chain B is wrong"
  exit 1
fi

echo "==== Start Hermes ===="
cargo run --bin hermes -- --config config_for_namada.toml \
  start > ${HERMES_DIR}/e2e/hermes.log 2>&1 &

echo "~~ Transfer 200 apfel from chain A to chain B ~~"
${NAMADAC} --base-dir ${base_dir_a} ibc-transfer \
  --source relayer \
  --receiver ${receiver_b} \
  --token apfel \
  --amount 200 \
  --signing-keys relayer \
  --channel-id channel-0 \
  --node ${LEDGER_ADDR_A}

echo "~~ Transfer 300 apfel from chain B to chain A ~~"
${NAMADAC} --base-dir ${base_dir_b} ibc-transfer \
  --source relayer \
  --receiver ${receiver_a} \
  --token apfel \
  --amount 300 \
  --signing-keys relayer \
  --channel-id channel-0 \
  --node ${LEDGER_ADDR_B}

wait_for_relaying ${chain_a}

echo "==== Balances on chain A ===="
balance=$(${NAMADAC} --base-dir ${base_dir_a} balance \
  --token apfel \
  --owner relayer \
  --node ${LEDGER_ADDR_A})
echo ${balance}
if [ "${balance}" != "apfel: 750" ]; then
  echo "The balance on chain A is wrong"
  exit 1
fi

balance=$(${NAMADAC} --base-dir ${base_dir_a} balance \
  --token ${IBC_TOKEN} \
  --owner relayer \
  --node ${LEDGER_ADDR_A})
echo ${balance}
if [ "${balance}" != "${IBC_TOKEN}: 300000000" ]; then
  echo "The balance on chain A is wrong"
  exit 1
fi

echo "==== Balances on chain B ===="
balance=$(${NAMADAC} --base-dir ${base_dir_b} balance \
  --token apfel \
  --owner relayer \
  --node ${LEDGER_ADDR_B})
echo ${balance}
if [ "${balance}" != "apfel: 700" ]; then
  echo "The balance on chain B is wrong"
  exit 1
fi

balance=$(${NAMADAC} --base-dir ${base_dir_b} balance \
  --token ${IBC_TOKEN} \
  --owner relayer \
  --node ${LEDGER_ADDR_B})
echo ${balance}
if [ "${balance}" != "${IBC_TOKEN}: 250000000" ]; then
  echo "The balance on chain B is wrong"
  exit 1
fi

echo "==== Shielded transfer tests ===="

echo "~~ Generate the proof from chain_b for the following transfer ~~"
resp=$(${NAMADAC} --base-dir ${base_dir_b} ibc-gen-shielding \
  --output-folder-path ${base_dir_b} \
  --target ${payment_addr_b} \
  --token apfel \
  --amount 100000000 \
  --port-id transfer \
  --channel-id channel-0 \
  --node ${LEDGER_ADDR_B})
memo_path=$(echo $resp | awk '{print $8}')

echo "~~ Shielded transfer 100 apfel from chain A to chain B ~~"
${NAMADAC} --base-dir ${base_dir_a} ibc-transfer \
  --source ${SHIELDED_ALIAS_A} \
  --receiver ${payment_addr_b} \
  --token apfel \
  --amount 100 \
  --channel-id channel-0 \
  --memo-path ${memo_path} \
  --gas-payer relayer \
  --node ${LEDGER_ADDR_A}

wait_for_relaying ${chain_a}

echo "==== Balance of shielded_a on chain A ===="
${NAMADAC} --base-dir ${base_dir_a} shielded-sync \
  --viewing-keys ${SHIELDED_ALIAS_A} \
  --node ${LEDGER_ADDR_A}
balance=$(${NAMADAC} --base-dir ${base_dir_a} balance \
  --token apfel \
  --owner ${SHIELDED_ALIAS_A} \
  --node ${LEDGER_ADDR_A})
echo "${balance}"
if [[ "${balance}" != *"apfel: 900" ]]; then
  echo "The balance of shielded_a on chain A is wrong"
  exit 1
fi

echo "==== Balance of shielded_b on chain B ===="
${NAMADAC} --base-dir ${base_dir_b} shielded-sync \
  --viewing-keys ${SHIELDED_ALIAS_B} \
  --node ${LEDGER_ADDR_B}
balance=$(${NAMADAC} --base-dir ${base_dir_b} balance \
  --token ${IBC_TOKEN} \
  --owner ${SHIELDED_ALIAS_B} \
  --node ${LEDGER_ADDR_B})
echo "${balance}"
if [[ "${balance}" != *"${IBC_TOKEN}: 100000000" ]]; then
  echo "The balance of shielded_b on chain B is wrong"
  exit 1
fi

echo "~~ Shielded transfer 50 apfel from shielded_b to shielded_b_2 ~~"
${NAMADAC} --base-dir ${base_dir_b} transfer \
  --source ${SHIELDED_ALIAS_B} \
  --target ${payment_addr_b_2} \
  --token ${IBC_TOKEN} \
  --amount 50000000 \
  --signing-keys relayer \
  --node ${LEDGER_ADDR_B}

echo "==== Balance of shielded_b on chain B ===="
${NAMADAC} --base-dir ${base_dir_b} shielded-sync \
  --viewing-keys ${SHIELDED_ALIAS_B} \
  --node ${LEDGER_ADDR_B}
balance=$(${NAMADAC} --base-dir ${base_dir_b} balance \
  --token ${IBC_TOKEN} \
  --owner ${SHIELDED_ALIAS_B} \
  --node ${LEDGER_ADDR_B})
echo "${balance}"
if [[ "${balance}" != *"${IBC_TOKEN}: 50000000" ]]; then
  echo "The balance of shielded_b on chain B is wrong"
  exit 1
fi

echo "==== Balance of shielded_b_2 on chain B ===="
${NAMADAC} --base-dir ${base_dir_b} shielded-sync \
  --viewing-keys ${SHIELDED_ALIAS_B_2} \
  --node ${LEDGER_ADDR_B}
balance=$(${NAMADAC} --base-dir ${base_dir_b} balance \
  --token ${IBC_TOKEN} \
  --owner ${SHIELDED_ALIAS_B_2} \
  --node ${LEDGER_ADDR_B})
echo "${balance}"
if [[ "${balance}" != *"${IBC_TOKEN}: 50000000" ]]; then
  echo "The balance of shielded_b_2 on chain B is wrong"
  exit 1
fi

echo "~~ Generate the proof from chain A for the following transfer ~~"
resp=$(${NAMADAC} --base-dir ${base_dir_a} ibc-gen-shielding \
  --output-folder-path ${base_dir_a} \
  --target ${payment_addr_a} \
  --token ${IBC_TOKEN} \
  --amount 50000000 \
  --port-id transfer \
  --channel-id channel-0 \
  --node ${LEDGER_ADDR_A})
memo_path=$(echo $resp | awk '{print $8}')

echo "~~ Transfer back 50 apfel from shielded_b_2 on chain B to chain A ~~"
${NAMADAC} --base-dir ${base_dir_b} ibc-transfer \
  --source ${SHIELDED_ALIAS_B_2} \
  --receiver ${payment_addr_a} \
  --token ${IBC_TOKEN} \
  --amount 50000000 \
  --signing-keys relayer \
  --channel-id channel-0 \
  --memo-path ${memo_path} \
  --node ${LEDGER_ADDR_B}

wait_for_relaying ${chain_a}

echo "==== Balances of shielded_a on chain A ===="
${NAMADAC} --base-dir ${base_dir_a} shielded-sync \
  --viewing-keys ${SHIELDED_ALIAS_A} \
  --node ${LEDGER_ADDR_A}
balance=$(${NAMADAC} --base-dir ${base_dir_a} balance \
  --token apfel \
  --owner ${SHIELDED_ALIAS_A} \
  --node ${LEDGER_ADDR_A})
echo "${balance}"
if [[ "${balance}" != *"apfel: 950" ]]; then
  echo "The balance of shielded_a on chain A is wrong"
  exit 1
fi

echo "==== Balances of shielded_b on chain B ===="
balance=$(${NAMADAC} --base-dir ${base_dir_b} balance \
  --token ${IBC_TOKEN} \
  --owner ${SHIELDED_ALIAS_B} \
  --node ${LEDGER_ADDR_B})
echo "${balance}"
if [[ "${balance}" != *"${IBC_TOKEN}: 50000000" ]]; then
  echo "The balance of shielded_b on chain B is wrong"
  exit 1
fi

echo "==== Balance of shielded_b_2 on chain B ===="
balance=$(${NAMADAC} --base-dir ${base_dir_b} balance \
  --token ${IBC_TOKEN} \
  --owner ${SHIELDED_ALIAS_B_2} \
  --node ${LEDGER_ADDR_B})
echo "${balance}"
if [[ "${balance}" != *"${IBC_TOKEN}: 0" ]]; then
  echo "The balance of shielded_b_2 on chain B is wrong"
  exit 1
fi

killall hermes
killall namadan
