#!/bin/bash

# This script executes simple transfers between Namada instances locally
# `make build` and `make build-wasm-scripts` on Namada directory in advance
# Run with `namada-simple-transfers ${namada_dir}`

set -e

NAMADA_DIR=$1
if [ -z "${NAMADA_DIR}" ]
then
  echo "ERROR: Namada directory should be given"
  exit 1
fi
cd $(dirname $0)
HERMES_DIR=${PWD%/e2e*}

NAMADAC="${NAMADA_DIR}/target/debug/namadac"
NAMADAW="${NAMADA_DIR}/target/debug/namadaw"
DATA_DIR="${HERMES_DIR}/data"

LEDGER_ADDR_A="http://127.0.0.1:27657"
LEDGER_ADDR_B="http://127.0.0.1:28657"
INITIAL_BALANCE=5000

function init_relayer_balance() {
  local suffix=$1
  local ledger_addr=$2

  local base_dir=${DATA_DIR}/namada-${suffix}

  ${NAMADAC} --base-dir ${base_dir} \
    transfer \
    --source albert \
    --target relayer \
    --token nam \
    --amount ${INITIAL_BALANCE} \
    --node ${ledger_addr}
}

# ==== main ====

# Run 2 Namada chains
${HERMES_DIR}/scripts/setup-namada ${NAMADA_DIR}

cd ${HERMES_DIR}
ids=$(grep "id" config_for_namada.toml | awk -F"'" '/^id/ {print $2}')
chain_a=$(echo ${ids} | awk '{print $1}')
chain_b=$(echo ${ids} | awk '{print $2}')

# Initialize the balances
init_relayer_balance "a" ${LEDGER_ADDR_A}
init_relayer_balance "b" ${LEDGER_ADDR_B}

# Create a channel
cargo run --bin hermes -- --config config_for_namada.toml \
  create channel \
  --a-chain ${chain_a} \
  --b-chain ${chain_b} \
  --a-port transfer \
  --b-port transfer \
  --new-client-connection --yes

# faucet apfel on chain_a and chain_b
base_dir_a=${DATA_DIR}/namada-a
base_dir_b=${DATA_DIR}/namada-b
${NAMADAC} --base-dir ${base_dir_a} transfer \
  --source albert \
  --target relayer \
  --token apfel \
  --amount 1000 \
  --signing-keys albert-key \
  --node ${LEDGER_ADDR_A}

${NAMADAC} --base-dir ${base_dir_b} transfer \
  --source albert \
  --target relayer \
  --token apfel \
  --amount 1000 \
  --signing-keys albert-key \
  --node ${LEDGER_ADDR_B}

# Get the receiver addresses
receiver_a=$(${NAMADAW} --base-dir ${base_dir_a} find --alias relayer | awk '/"relayer":/{print $3}')
receiver_b=$(${NAMADAW} --base-dir ${base_dir_b} find --alias relayer | awk '/"relayer":/{print $3}')

echo "~~ Transfer 100 apfel from chain_a to chain_b ~~"
${NAMADAC} --base-dir ${base_dir_a} ibc-transfer \
  --source relayer \
  --receiver ${receiver_b} \
  --token apfel \
  --amount 100 \
  --signing-keys relayer \
  --channel-id channel-0 \
  --node ${LEDGER_ADDR_A}

# packet-recv
cargo run --bin hermes -- --config config_for_namada.toml \
  tx packet-recv \
  --dst-chain ${chain_b} \
  --src-chain ${chain_a} \
  --src-port transfer \
  --src-channel channel-0

# packet-ack
cargo run --bin hermes -- --config config_for_namada.toml \
  tx packet-ack \
  --dst-chain ${chain_a} \
  --src-chain ${chain_b} \
  --src-port transfer \
  --src-channel channel-0

echo "==== Balances on chain A ===="
${NAMADAC} --base-dir ${base_dir_a} balance \
  --token apfel \
  --owner relayer \
  --show-ibc-tokens \
  --node ${LEDGER_ADDR_A}

echo "==== Balances on chain B ===="
${NAMADAC} --base-dir ${base_dir_b} balance \
  --owner relayer \
  --show-ibc-tokens \
  --node ${LEDGER_ADDR_B}
# get token address
received_token=$(${NAMADAC} --base-dir ${base_dir_b} balance \
  --owner relayer \
  --show-ibc-tokens \
  --node ${LEDGER_ADDR_B} \
  | sed -e s/://g \
  | awk '$1 ~ /transfer\/channel-0/ {print $1}')

echo "~~ Transfer back 50 apfel from chain_b to chain_a ~~"
${NAMADAC} --base-dir ${base_dir_b} ibc-transfer \
  --source relayer \
  --receiver ${receiver_a} \
  --token ${received_token} \
  --amount 50 \
  --signing-keys relayer \
  --channel-id channel-0 \
  --node ${LEDGER_ADDR_B}

# packet-recv
cargo run --bin hermes -- --config config_for_namada.toml \
  tx packet-recv \
  --dst-chain ${chain_a} \
  --src-chain ${chain_b} \
  --src-port transfer \
  --src-channel channel-0

# packet-ack
cargo run --bin hermes -- --config config_for_namada.toml \
  tx packet-ack \
  --dst-chain ${chain_b} \
  --src-chain ${chain_a} \
  --src-port transfer \
  --src-channel channel-0

echo "==== Balances on chain A ===="
${NAMADAC} --base-dir ${base_dir_a} balance \
  --token apfel \
  --owner relayer \
  --show-ibc-tokens \
  --node ${LEDGER_ADDR_A}

echo "==== Balances on chain B ===="
${NAMADAC} --base-dir ${base_dir_b} balance \
  --token ${received_token} \
  --owner relayer \
  --show-ibc-tokens \
  --node ${LEDGER_ADDR_B}

echo "==== Start Hermes ===="
cargo run --bin hermes -- --config config_for_namada.toml \
  start > ${HERMES_DIR}/e2e/hermes.log 2>&1 &

echo "~~ Transfer 200 apfel from chain_a to chain_b ~~"
${NAMADAC} --base-dir ${base_dir_a} ibc-transfer \
  --source relayer \
  --receiver ${receiver_b} \
  --token apfel \
  --amount 200 \
  --signing-keys relayer \
  --channel-id channel-0 \
  --node ${LEDGER_ADDR_A}

echo "~~ Transfer 300 apfel from chain_b to chain_a ~~"
${NAMADAC} --base-dir ${base_dir_b} ibc-transfer \
  --source relayer \
  --receiver ${receiver_a} \
  --token apfel \
  --amount 300 \
  --signing-keys relayer \
  --channel-id channel-0 \
  --node ${LEDGER_ADDR_B}

# wait for relaying
sleep 15

echo "==== Balances on chain A ===="
${NAMADAC} --base-dir ${base_dir_a} balance \
  --owner relayer \
  --show-ibc-tokens \
  --node ${LEDGER_ADDR_A}

echo "==== Balances on chain B ===="
${NAMADAC} --base-dir ${base_dir_b} balance \
  --owner relayer \
  --show-ibc-tokens \
  --node ${LEDGER_ADDR_B}

killall hermes
killall namadan
