#!/bin/bash

# This script executes Hermes' E2E test for Namada locally
# `make build-release` and `make build-wasm-scripts` on Namada directory in advance
# Run with `namada-e2e-test ${namada_dir}`

set -xe

NAMADA_DIR=$1
if [ -z "${NAMADA_DIR}" ]
then
  echo "ERROR: Namada directory should be given"
  exit 1
fi
cd $(dirname $0)
HERMES_DIR=${PWD%/e2e*}

NAMADAC="${NAMADA_DIR}/target/release/namadac"
DATA_DIR="${HERMES_DIR}/data"
E2E_TEST_LOG="ibc_e2e.log"

LEDGER_ADDR_A="127.0.0.1:27657"
LEDGER_ADDR_B="127.0.0.1:28657"
INITIAL_BALANCE=10000

function init_relayer_balance() {
  local suffix=$1
  local ledger_addr=$2

  local base_dir=${DATA_DIR}/namada-${suffix}/.namada

  local cnt=0
  local cnt_max=$((${INITIAL_BALANCE} / 1000))
  while [ ${cnt} -lt ${cnt_max} ]
  do
      ${NAMADAC} --base-dir ${base_dir} \
        transfer \
        --source faucet \
        --target relayer \
        --token nam \
        --amount 1000 \
        --signing-keys relayer \
        --node ${ledger_addr}

      cnt=$((${cnt} + 1))
  done
}

# ==== main ====

# Run 2 Namada chains
${HERMES_DIR}/scripts/setup-namada ${NAMADA_DIR}

# Initialize the balances
init_relayer_balance "a" ${LEDGER_ADDR_A}
init_relayer_balance "b" ${LEDGER_ADDR_B}

cd ${HERMES_DIR}
python3 e2e/run.py --config ${HERMES_DIR}/config_for_namada.toml 2>&1 | tee e2e/${E2E_TEST_LOG}

killall namadan
