use ibc_proto::cosmos::tx::v1beta1::{AuthInfo, TxBody};
use tendermint_rpc::endpoint::broadcast::tx_sync::Response;

use crate::event::IbcEventWithHeight;

pub struct SignedTx {
    pub body: TxBody,
    pub body_bytes: Vec<u8>,
    pub auth_info: AuthInfo,
    pub auth_info_bytes: Vec<u8>,
    pub signatures: Vec<Vec<u8>>,
}

pub enum TxStatus {
    Pending { message_count: usize },
    ReceivedResponse,
}

pub struct TxSyncResult {
    // the broadcast_tx_sync response
    pub response: Response,
    // the events generated by a Tx once executed
    pub events: Vec<IbcEventWithHeight>,
    pub status: TxStatus,
}
