use ibc::events::IbcEvent;
use tendermint_rpc::endpoint::broadcast::tx_sync::Response;

pub struct TxSyncResult {
    // the broadcast_tx_sync response
    pub response: Response,
    // the events generated by a Tx once executed
    pub events: Vec<IbcEvent>,
}
