#!/bin/bash -e

# Copied from https://github.com/cosmos/relayer and modified to initialize Gaia chains.

usage() {
  echo "Usage: $0 CHAIN_0_ID CHAIN_1_ID [CHAIN_2_ID]"
  echo "Example: $0 ibc-0 ibc-1 ibc-2"
  exit 1
}

missing() {
  echo "Missing $1 parameter. Please check if all parameters were specified."
  usage
}

if [ -z "$1" ]; then
  missing "CHAIN_0_ID"
fi

if [ -z "$2" ]; then
  missing "CHAIN_1_ID"
fi


if [ "$#" -gt 3 ]; then
  echo "Incorrect number of parameters."
  usage
fi

CHAIN_0_ID="$1"
CHAIN_1_ID="$2"
CHAIN_2_ID="$3"

GAIA_DATA="$(pwd)/data"

# Ensure user understands what will be deleted
if [[ -d $GAIA_DATA ]] && [[ ! "$3" == "skip" ]]; then
  echo "WARNING: $0 will DELETE the '$(pwd)/data' folder."
  read -p "> Do you wish to continue? (y/n): " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
      exit 1
  fi
fi

# Ensure gaiad is installed
if ! [ -x "$(which gaiad)" ]; then
  echo "Error: gaiad is not installed. Try running 'make build-gaia'" >&2
  exit 1
fi

# Display software version
echo "GAIA VERSION INFO: $(gaiad version --log_level info)"

# Delete data from old runs
echo "Deleting $GAIA_DATA folder..."
rm -rf "$GAIA_DATA"

# Stop existing gaiad processes
killall gaiad &> /dev/null || true
killall akash &> /dev/null || true

echo "Generating gaia configurations..."
mkdir -p "$GAIA_DATA" && cd "$GAIA_DATA" && cd ../

ONE_CHAIN="$(dirname "$0")/one-chain"

CHAIN_0_RPC_PORT=26657
CHAIN_1_RPC_PORT=26557
CHAIN_2_RPC_PORT=26457

CHAIN_0_GRPC_PORT=9090
CHAIN_1_GRPC_PORT=9091
CHAIN_2_GRPC_PORT=9092

CHAIN_0_SAMOLEANS=100000000000
CHAIN_1_SAMOLEANS=100000000000
CHAIN_2_SAMOLEANS=100000000000

"$ONE_CHAIN" gaiad "$CHAIN_0_ID" ./data $CHAIN_0_RPC_PORT 26656 6060 $CHAIN_0_GRPC_PORT $CHAIN_0_SAMOLEANS
"$ONE_CHAIN" gaiad "$CHAIN_1_ID" ./data $CHAIN_1_RPC_PORT 26556 6061 $CHAIN_1_GRPC_PORT $CHAIN_1_SAMOLEANS

if [ -n "$CHAIN_2_ID" ]; then
  "$ONE_CHAIN" gaiad "$CHAIN_2_ID" ./data $CHAIN_2_RPC_PORT 26456 6062 $CHAIN_2_GRPC_PORT $CHAIN_2_SAMOLEANS
fi

[ -f "$GAIA_DATA/$CHAIN_0_ID.log" ] && echo "$CHAIN_0_ID initialized. Watch file $GAIA_DATA/$CHAIN_0_ID.log to see its execution."
[ -f "$GAIA_DATA/$CHAIN_1_ID.log" ] && echo "$CHAIN_1_ID initialized. Watch file $GAIA_DATA/$CHAIN_1_ID.log to see its execution."

if [ -n "$CHAIN_2_ID" ]; then
  [ -f "$GAIA_DATA/$CHAIN_2_ID.log" ] && echo "$CHAIN_2_ID initialized. Watch file $GAIA_DATA/$CHAIN_2_ID.log to see its execution."
fi
