#!/bin/bash

# This script sets up 1 Namada chain locally
# `make build` and `make build-wasm-scripts` on Namada directory in advance
# Run with `setup-namada-single-node ${namada_dir}`

set -e

NAMADA_DIR=$1
if [ -z "${NAMADA_DIR}" ]
then
  echo "ERROR: Namada directory should be given"
  exit 1
fi
cd $(dirname $0)
HERMES_DIR=${PWD%/scripts*}

# edit for your environment
NAMADAC="${NAMADA_DIR}/target/debug/namadac"
NAMADAN="${NAMADA_DIR}/target/debug/namadan"
NAMADAW="${NAMADA_DIR}/target/debug/namadaw"
BASE_GENESIS_DIR="${NAMADA_DIR}/genesis/localnet"
CHECKSUM_PATH="${NAMADA_DIR}/wasm/checksums.json"
DATA_DIR="${HERMES_DIR}/data"

LEDGER_ADDR="http://127.0.0.1:27657"

HERMES_CONFIG_TEMPLATE="
[global]
log_level = 'info'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 10
clear_on_start = false
tx_confirmation = true

[telemetry]
enabled = false
host = '127.0.0.1'
port = 3001

[[chains]]
id = '_CHAIN_ID_'
type = 'Namada'
rpc_addr = 'http://127.0.0.1:27657'
grpc_addr = 'http://127.0.0.1:9090'
event_source = { mode = 'push', url = 'ws://127.0.0.1:27657/websocket', batch_delay = '500ms' }
account_prefix = ''
key_name = 'relayer'
store_prefix = 'ibc'
gas_price = { price = 0.001, denom = '_FEE_TOKEN_' }
"

function make_genesis() {
  local base_dir=${DATA_DIR}/namada

  mkdir -p ${base_dir}/templates
  cp ${BASE_GENESIS_DIR}/*.toml ${base_dir}/templates
  sed -i .bak "s/epochs_per_year = .*/epochs_per_year = 31536/g" ${base_dir}/templates/parameters.toml
  sed -i .bak "s/default_mint_limit = .*/default_mint_limit = \"1000000000\"/g" ${base_dir}/templates/parameters.toml
  sed -i .bak "s/default_per_epoch_throughput_limit = .*/default_per_epoch_throughput_limit = \"1000000000\"/g" ${base_dir}/templates/parameters.toml

  mkdir ${base_dir}/pre-genesis
  cp -r ${BASE_GENESIS_DIR}/src/pre-genesis/* ${base_dir}/pre-genesis
}

function init_network() {
  local base_dir=${DATA_DIR}/namada
  local validator_base_dir=${base_dir}/setup/validator-0

  mkdir -p ${base_dir}/genesis
  local chain_id=$(NAMADA_BASE_DIR=${base_dir} \
    ${NAMADAC} utils init-network \
    --chain-prefix namada-test \
    --genesis-time "2023-01-01T00:00:00Z" \
    --templates-path ${base_dir}/templates \
    --wasm-checksums-path ${CHECKSUM_PATH} \
    --archive-dir ${base_dir}/genesis \
    | awk '$1 == "Derived" {print $4}')

  NAMADA_NETWORK_CONFIGS_DIR=${base_dir}/genesis \
  ${NAMADAC} --base-dir ${validator_base_dir} \
    utils join-network \
    --chain-id ${chain_id} \
    --genesis-validator validator-0 \
    --pre-genesis-path \
    ${base_dir}/pre-genesis/validator-0 \
    --dont-prefetch-wasm

  # for non-validator
  rm -rf ${base_dir}/${chain_id}
  NAMADA_NETWORK_CONFIGS_DIR=${base_dir}/genesis \
  ${NAMADAC} --base-dir ${base_dir} \
  utils join-network \
  --chain-id ${chain_id} \
  --dont-prefetch-wasm
}

function copy_wasm() {
  local chain_id=$1
  local base_dir=${DATA_DIR}/namada

  cp ${NAMADA_DIR}/wasm/*.wasm ${base_dir}/setup/validator-0/${chain_id}/wasm/
}

function init_relayer_acc() {
  local chain_id=$1

  local base_dir=${DATA_DIR}/namada

  ${NAMADAW} --base-dir ${base_dir} \
    gen --alias relayer --unsafe-dont-encrypt
}

function fund_relayer_acc() {
  local account=$1
  local base_dir=${DATA_DIR}/namada

  ${NAMADAC} --base-dir ${base_dir} \
    transfer --node ${LEDGER_ADDR} \
    --source ${account} --target relayer --amount 10000 --token NAM
}

function add_relayer_key() {
  local chain_id=$1

  local base_dir=${DATA_DIR}/namada

  cargo run --bin hermes -- --config ${HERMES_DIR}/config_for_namada.toml \
    keys add \
    --chain ${chain_id} \
    --key-file ${base_dir}/${chain_id}/wallet.toml \
    --overwrite
}

# ==== main ====

mkdir -p ${DATA_DIR}

make_genesis
result=$(init_network)
chain_id=$(echo "${result}" | awk '$5 == "ID" {id = $6} END {print id}')

copy_wasm ${chain_id}

${NAMADAN} --base-dir ${DATA_DIR}/namada/setup/validator-0 \
  ledger run > ${DATA_DIR}/namada/namada.log 2>&1 &
echo "Namada chain's PID = $!"
sleep 5

init_relayer_acc ${chain_id}
sleep 10

fund_relayer_acc "albert" ${LEDGER_ADDR}

nam_addr=$(${NAMADAW} --base-dir ${DATA_DIR}/namada find --alias nam | awk '/"nam":/{print $3}')

# for the relayer
cd ${HERMES_DIR}
echo "${HERMES_CONFIG_TEMPLATE}" \
  | sed -e "s/_CHAIN_ID_/${chain_id}/g" -e "s/_FEE_TOKEN_/${nam_addr}/g" \
  > ${HERMES_DIR}/config_for_namada.toml

add_relayer_key ${chain_id}

echo "A Namada chain is running"
echo "You can use Hermes with ${HERMES_DIR}/config_for_namada.toml"

echo "You also want to run the following lines:"
echo "export CHAIN_ID=${chain_id}"
